import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // fetch("http://localhost:9999/topics")
  //   .then((res) => res.json())
  //   .then((result) => {
  //     setTopics(result);
  //   });

  // const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
  //   next: { revalidate: 0 },
  // });
  // const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {/* {topics.map((item) => {
            return (
              <li key={item.id}>
                <Link href={`/read/${item.id}`}>{item.body}</Link>
              </li>
            );
          })} */}
        </ol>
        {children}
        {/* <Control /> */}
      </body>
    </html>
  );
}
